ezplatform_page_fieldtype:
    blocks:
        gallery:
            attributes:
                contentId:
                    validators:
                        content_type:
                            message: You must select a Folder or Gallery
                            options:
                                types: ['folder', 'gallery']
        video:
            attributes:
                contentId:
                    validators:
                        content_type:
                            message: You must select an Video
                            options:
                                types: video

#        hero:
#            name: Hero
#            category: default
#            thumbnail: '/assets/images/page_builder/blocks/hero.svg#hero'
#            configuration_template: '@EzPlatformPageBuilder/page_builder/block/config/embed.html.twig'
#            attributes:
#                text:
#                    name: Text
#                    type: text
#                    validators:
#                        not_blank:
#                            message: You must provide a text
#                        regexp:
#                            options:
#                                pattern: '/[^\\s]/'
#                            message: Only valid HTML code is allowed
#                contentId:
#                    name: Image
#                    type: embed
#                    validators:
#                        not_blank:
#                            message: You must provide value
#                        regexp:
#                            options:
#                                pattern: '/[0-9]+/'
#                            message: Choose a Content item
#                        content_type:
#                            message: You must select an Image
#                            options:
#                                types: image
#
