v: 0

# VL teA
# foobar
# kake2

# ci
integrate:
  command: "bin/behat"
  matrix:
  # Run 'common' tagged behat scenarios on ezplatform-ee-demo install
   - {arguments: "-v --profile demoMeta --tags common --strict", install: "demo"}

