login:
    path: /login
    defaults: { _controller: ezpublish.security.controller:loginAction }

login_check:
    path: /login_check

logout:
    path: /logout

app.search:
    path: /content/search
    defaults:
        _controller: app.controller.search:showSearchResultsAction
    methods: [GET]

app.subscribe:
    path: /Subscribe
    defaults:
        _controller: app.controller.subscribe:confirm
    methods: [POST]

app.user_preferences:
    path: /user/preferences
    defaults:
        _controller: app.controller.user_profile_controller:showPreferencesAction
    methods: [GET, POST]

netgen_tags_admin_autocomplete:
    path: /tags/admin/field/autocomplete
    defaults:
        _controller: eztags.admin.controller.field:autoCompleteAction
        _method: GET
    options:
        expose: true

kernel.internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

kernel.rest:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: /api/ezp/v2

ezplatform.admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

_ezplatformRepositoryFormsRoutes:
    resource: '@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml'

ezplatform.ee.dependencies.bazinga:
    resource: '@BazingaJsTranslationBundle/Resources/config/routing/routing.yml'

ezplatform.ee.dependencies.platform_ui:
    resource: '@eZPlatformUIBundle/Resources/config/routing.yml'

ezplatform.ee.admin_ui:
    resource: '@eZStudioUIBundle/Resources/config/routing.yml'

ezplatform.ee.form_builder:
    resource: '@EzSystemsFormBuilderBundle/Resources/config/routing.yml'

ezplatform.ee.date_based_publisher:
    resource: '@EzSystemsDateBasedPublisherBundle/Resources/config/routing.yml'
    prefix: '%ez_systems_date_based_publisher_rest_prefix%'

ezplatform.ee.flex_workflow:
    resource: '@FlexWorkflowBundle/Resources/config/routing.yml'

ezplatform.ee.notifications:
    resource: '@NotificationBundle/Resources/config/routing.yml'

ezplatform.ee.landing_page:
    resource: '@EzSystemsLandingPageFieldTypeBundle/Resources/config/routing.yml'

fos.js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

_eztagsRoutes:
    resource: "@NetgenTagsBundle/Resources/config/routing.yml"

_novaezseoRoutes:
    resource: "@NovaeZSEOBundle/Controller/"
    type:     annotation
    prefix:   /

recommendationBundleRestRoutes:
    resource: "@EzSystemsRecommendationBundle/Resources/config/routing_rest.yml"
    prefix:   %ezpublish_rest.path_prefix%

_personalizedBlockRoutes:
     resource: "@EzSystemsPersonalizedBlockBundle/Resources/config/routing.yml"

# Custom redirection from /ez to /admin, feel free to adjust to your needs or remove if you don't need it
platform1_admin_route:
    path: /ez
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true
