# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

imports:
    - { resource: services/cache.yaml }
    - { resource: services/content.yaml }
    - { resource: services/controllers.yaml }
    - { resource: services/events.yaml }
    - { resource: services/helpers.yaml }
    - { resource: services/installer.yaml }
    - { resource: services/layout.yaml }
    - { resource: services/mailer.yaml }
    - { resource: services/migration.yaml }
    - { resource: services/pagerfanta.yaml }
    - { resource: services/query_types.yaml }
    - { resource: services/search.yaml }
    - { resource: services/twig.yaml }

parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Those service definitions were added to fix missing command registration in an external package
    JMS\TranslationBundle\Command\ExtractTranslationCommand:
        tags:
            - { name: console.command }

    JMS\TranslationBundle\Command\ResourcesListCommand:
        tags:
            - { name: console.command }
