version: '3.2'

services:
  db:
    image: mariadb:10.1
    volumes:
     - ./doc/docker-compose/entrypoint/mysql/0_database_character_set.sh:/docker-entrypoint-initdb.d/0_database_character_set.sh:ro
    # Fixme : may we use environment variables from .env if we generate a bundle ?
    environment:
     - MYSQL_RANDOM_ROOT_PASSWORD=1
     - MYSQL_USER=ezp
     - MYSQL_PASSWORD=SetYourOwnPassword
     - MYSQL_DATABASE=ezp
     - TERM=dumb
    networks:
     - db

networks:
  db:
     attachable: true